Handle no-op and artifical dl on unarchive
clowder-framework/extractors-archival pull request #7
Opened 2021-05-24 19:28 UTC by bodom0015

## Problem
* Files that have been automatically archived, and then manually unarchived, will be re-archived when the auto-archive next runs
* It is possible to trigger Archive on an Archived file - this results in a needless copy (which on S3, could cost money)

## Approach
* Trigger a silent download when unarchiving
* Handle the no-op case properly and return

2021-05-24 19:41 UTC, robkooper requested changes

2021-05-24 19:41 UTC, robkooper commented on archival-disk/disk-archival.py
> +        # Trigger a download of this file (so that auto-archival doesn't immediately re-archive it)
lets just do this in clowder when we mark the file is unarchived.

2021-05-24 20:36 UTC, bodom0015 commented
Updated this PR to remove the artificial download on unarchive - this will be handled by Clowder (see https://github.com/clowder-framework/clowder/pull/234)

2021-07-14 14:53 UTC, robkooper approved these changes

2021-07-14 14:54 UTC, robkooper requested changes
need to bump version number in extractor_info.json

2021-07-14 21:20 UTC, robkooper approved these changes

2021-07-14 21:21 UTC, merged